name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Enable Pages via PAT (optional)
        env:
          PAGES_PAT: ${{ secrets.PAGES_PAT }}
          REPO_FULL: ${{ github.repository }}
        run: |
          if [ -z "$PAGES_PAT" ]; then
            echo "PAGES_PAT not set — skipping PAT-based Pages enablement"
            exit 0
          fi
          echo "Enabling GitHub Pages via REST API using provided PAT..."
          api_url="https://api.github.com/repos/${REPO_FULL}/pages"
          body='{"source":{"branch":"main","path":"/"}}'
          curl -sS -X POST -H "Authorization: token $PAGES_PAT" -H "Accept: application/vnd.github+json" -d "$body" "$api_url" || true

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4